import random

def get_random_korean_word():
    """Get a random Korean word and its meaning from a predefined list."""
    words = [
        {"word": "안녕", "meaning": "Hello"},
        {"word": "감사합니다", "meaning": "Thank you"},
        {"word": "사랑", "meaning": "Love"},
        {"word": "친구", "meaning": "Friend"},
        {"word": "가족", "meaning": "Family"},
        {"word": "음식", "meaning": "Food"},
        {"word": "학교", "meaning": "School"},
        {"word": "책", "meaning": "Book"},
        {"word": "공부", "meaning": "Study"},
        {"word": "언어", "meaning": "Language"},
        {"word": "시간", "meaning": "Time"},
        {"word": "물", "meaning": "Water"},
        {"word": "길", "meaning": "Road"},
        {"word": "하늘", "meaning": "Sky"},
        {"word": "바다", "meaning": "Sea"},
        {"word": "산", "meaning": "Mountain"},
        {"word": "꽃", "meaning": "Flower"},
        {"word": "나무", "meaning": "Tree"},
        {"word": "음악", "meaning": "Music"},
        {"word": "영화", "meaning": "Movie"},
        {"word": "컴퓨터", "meaning": "Computer"},
        {"word": "전화", "meaning": "Phone"},
        {"word": "사과", "meaning": "Apple"},
        {"word": "바나나", "meaning": "Banana"},
        {"word": "커피", "meaning": "Coffee"},
        {"word": "차", "meaning": "Tea"},
        {"word": "일", "meaning": "Work"},
        {"word": "돈", "meaning": "Money"},
        {"word": "집", "meaning": "House"},
        {"word": "자동차", "meaning": "Car"},
        {"word": "여행", "meaning": "Travel"},
        {"word": "하루", "meaning": "Day"},
        {"word": "밤", "meaning": "Night"},
        {"word": "달", "meaning": "Moon"},
        {"word": "빛", "meaning": "Light"},
        {"word": "어둠", "meaning": "Darkness"},
        {"word": "색", "meaning": "Color"},
        {"word": "노래", "meaning": "Song"},
        {"word": "미소", "meaning": "Smile"},
        {"word": "웃음", "meaning": "Laughter"},
        {"word": "슬픔", "meaning": "Sadness"},
        {"word": "기쁨", "meaning": "Happiness"},
        {"word": "눈", "meaning": "Snow/Eye"},
        {"word": "비", "meaning": "Rain"},
        {"word": "바람", "meaning": "Wind"},
        {"word": "맛", "meaning": "Taste"},
        {"word": "향기", "meaning": "Fragrance"},
        {"word": "소리", "meaning": "Sound"},
        {"word": "문", "meaning": "Door"},
        {"word": "창문", "meaning": "Window"},
        
        # Additional nouns
        {"word": "귀", "meaning": "Ear"},
        {"word": "코", "meaning": "Nose"},
        {"word": "입", "meaning": "Mouth"},
        {"word": "손", "meaning": "Hand"},
        {"word": "발", "meaning": "Foot"},
        {"word": "머리", "meaning": "Head"},
        {"word": "다리", "meaning": "Leg"},
        {"word": "팔", "meaning": "Arm"},
        {"word": "가방", "meaning": "Bag"},
        {"word": "신발", "meaning": "Shoes"},
        {"word": "옷", "meaning": "Clothes"},
        {"word": "모자", "meaning": "Hat"},
        {"word": "안경", "meaning": "Glasses"},
        {"word": "시계", "meaning": "Watch/Clock"},
        {"word": "열쇠", "meaning": "Key"},
        {"word": "지갑", "meaning": "Wallet"},
        {"word": "우산", "meaning": "Umbrella"},
        {"word": "카드", "meaning": "Card"},
        {"word": "종이", "meaning": "Paper"},
        {"word": "펜", "meaning": "Pen"},
        {"word": "연필", "meaning": "Pencil"},
        {"word": "칼", "meaning": "Knife"},
        {"word": "포크", "meaning": "Fork"},
        {"word": "숟가락", "meaning": "Spoon"},
        {"word": "접시", "meaning": "Plate"},
        {"word": "컵", "meaning": "Cup"},
        {"word": "병", "meaning": "Bottle"},
        {"word": "치즈", "meaning": "Cheese"},
        {"word": "고기", "meaning": "Meat"},
        {"word": "생선", "meaning": "Fish"},
        {"word": "닭고기", "meaning": "Chicken"},
        {"word": "쇠고기", "meaning": "Beef"},
        {"word": "돼지고기", "meaning": "Pork"},
        {"word": "야채", "meaning": "Vegetables"},
        {"word": "과일", "meaning": "Fruit"},
        {"word": "빵", "meaning": "Bread"},
        {"word": "밥", "meaning": "Rice"},
        {"word": "국", "meaning": "Soup"},
        {"word": "술", "meaning": "Alcohol"},
        {"word": "주스", "meaning": "Juice"},
        {"word": "우유", "meaning": "Milk"},
        {"word": "소금", "meaning": "Salt"},
        {"word": "설탕", "meaning": "Sugar"},
        {"word": "후추", "meaning": "Pepper"},
        {"word": "지하철", "meaning": "Subway"},
        {"word": "버스", "meaning": "Bus"},
        {"word": "택시", "meaning": "Taxi"},
        {"word": "비행기", "meaning": "Airplane"},
        {"word": "배", "meaning": "Ship/Boat"},
        {"word": "자전거", "meaning": "Bicycle"},
        {"word": "호텔", "meaning": "Hotel"},
        {"word": "공항", "meaning": "Airport"},
        {"word": "역", "meaning": "Station"},
        {"word": "병원", "meaning": "Hospital"},
        {"word": "은행", "meaning": "Bank"},
        {"word": "우체국", "meaning": "Post Office"},
        {"word": "시장", "meaning": "Market"},
        {"word": "백화점", "meaning": "Department Store"},
        {"word": "약국", "meaning": "Pharmacy"},
        {"word": "화장실", "meaning": "Bathroom"},
        {"word": "주방", "meaning": "Kitchen"},
        {"word": "거실", "meaning": "Living Room"},
        {"word": "침실", "meaning": "Bedroom"},
        {"word": "계단", "meaning": "Stairs"},
        {"word": "엘리베이터", "meaning": "Elevator"},
        {"word": "천장", "meaning": "Ceiling"},
        {"word": "바닥", "meaning": "Floor"},
        {"word": "벽", "meaning": "Wall"},
        {"word": "방", "meaning": "Room"},
        
        # Adjectives
        {"word": "좋다", "meaning": "Good"},
        {"word": "나쁘다", "meaning": "Bad"},
        {"word": "크다", "meaning": "Big"},
        {"word": "작다", "meaning": "Small"},
        {"word": "많다", "meaning": "Many/Much"},
        {"word": "적다", "meaning": "Few/Little"},
        {"word": "높다", "meaning": "High/Tall"},
        {"word": "낮다", "meaning": "Low/Short"},
        {"word": "길다", "meaning": "Long"},
        {"word": "짧다", "meaning": "Short"},
        {"word": "무겁다", "meaning": "Heavy"},
        {"word": "가볍다", "meaning": "Light (weight)"},
        {"word": "뜨겁다", "meaning": "Hot"},
        {"word": "차갑다", "meaning": "Cold"},
        {"word": "따뜻하다", "meaning": "Warm"},
        {"word": "시원하다", "meaning": "Cool/Refreshing"},
        {"word": "새롭다", "meaning": "New"},
        {"word": "오래되다", "meaning": "Old (thing)"},
        {"word": "늙다", "meaning": "Old (person)"},
        {"word": "젊다", "meaning": "Young"},
        {"word": "아름답다", "meaning": "Beautiful"},
        {"word": "예쁘다", "meaning": "Pretty"},
        {"word": "잘생기다", "meaning": "Handsome"},
        {"word": "못생기다", "meaning": "Ugly"},
        {"word": "깨끗하다", "meaning": "Clean"},
        {"word": "더럽다", "meaning": "Dirty"},
        {"word": "쉽다", "meaning": "Easy"},
        {"word": "어렵다", "meaning": "Difficult"},
        {"word": "비싸다", "meaning": "Expensive"},
        {"word": "싸다", "meaning": "Cheap"},
        {"word": "맛있다", "meaning": "Delicious"},
        {"word": "맛없다", "meaning": "Not tasty"},
        {"word": "행복하다", "meaning": "Happy"},
        {"word": "슬프다", "meaning": "Sad"},
        {"word": "화나다", "meaning": "Angry"},
        {"word": "피곤하다", "meaning": "Tired"},
        {"word": "바쁘다", "meaning": "Busy"},
        {"word": "한가하다", "meaning": "Free/Not busy"},
        {"word": "똑똑하다", "meaning": "Smart"},
        {"word": "멍청하다", "meaning": "Stupid"},
        {"word": "강하다", "meaning": "Strong"},
        {"word": "약하다", "meaning": "Weak"},
        {"word": "빠르다", "meaning": "Fast"},
        {"word": "느리다", "meaning": "Slow"},
        {"word": "재미있다", "meaning": "Interesting/Fun"},
        {"word": "지루하다", "meaning": "Boring"},
        {"word": "친절하다", "meaning": "Kind"},
        {"word": "불친절하다", "meaning": "Unkind"},
        {"word": "조용하다", "meaning": "Quiet"},
        {"word": "시끄럽다", "meaning": "Noisy"},
        {"word": "두껍다", "meaning": "Thick"},
        {"word": "얇다", "meaning": "Thin (object)"},
        {"word": "마르다", "meaning": "Thin/Skinny (person)"},
        {"word": "뚱뚱하다", "meaning": "Fat"},
        
        # Verbs
        {"word": "가다", "meaning": "To go"},
        {"word": "오다", "meaning": "To come"},
        {"word": "먹다", "meaning": "To eat"},
        {"word": "마시다", "meaning": "To drink"},
        {"word": "자다", "meaning": "To sleep"},
        {"word": "일어나다", "meaning": "To wake up"},
        {"word": "보다", "meaning": "To see/watch"},
        {"word": "듣다", "meaning": "To listen/hear"},
        {"word": "말하다", "meaning": "To speak"},
        {"word": "읽다", "meaning": "To read"},
        {"word": "쓰다", "meaning": "To write"},
        {"word": "배우다", "meaning": "To learn"},
        {"word": "가르치다", "meaning": "To teach"},
        {"word": "주다", "meaning": "To give"},
        {"word": "받다", "meaning": "To receive"},
        {"word": "사다", "meaning": "To buy"},
        {"word": "팔다", "meaning": "To sell"},
        {"word": "만들다", "meaning": "To make"},
        {"word": "찾다", "meaning": "To find/look for"},
        {"word": "잃다", "meaning": "To lose"},
        {"word": "열다", "meaning": "To open"},
        {"word": "닫다", "meaning": "To close"},
        {"word": "시작하다", "meaning": "To start"},
        {"word": "끝내다", "meaning": "To finish"},
        {"word": "웃다", "meaning": "To laugh"},
        {"word": "울다", "meaning": "To cry"},
        {"word": "앉다", "meaning": "To sit"},
        {"word": "서다", "meaning": "To stand"},
        {"word": "걷다", "meaning": "To walk"},
        {"word": "뛰다", "meaning": "To run"},
        {"word": "놀다", "meaning": "To play"},
        {"word": "일하다", "meaning": "To work"},
        {"word": "쉬다", "meaning": "To rest"},
        {"word": "춤추다", "meaning": "To dance"},
        {"word": "노래하다", "meaning": "To sing"},
        {"word": "그리다", "meaning": "To draw"},
        {"word": "요리하다", "meaning": "To cook"},
        {"word": "씻다", "meaning": "To wash"},
        {"word": "입다", "meaning": "To wear"},
        {"word": "벗다", "meaning": "To take off (clothes)"},
        {"word": "기다리다", "meaning": "To wait"},
        {"word": "만나다", "meaning": "To meet"},
        {"word": "도와주다", "meaning": "To help"},
        {"word": "사용하다", "meaning": "To use"},
        {"word": "보내다", "meaning": "To send"},
        {"word": "받아들이다", "meaning": "To accept"},
        {"word": "거절하다", "meaning": "To refuse"},
        {"word": "믿다", "meaning": "To believe"},
        {"word": "생각하다", "meaning": "To think"},
        {"word": "알다", "meaning": "To know"},
        {"word": "모르다", "meaning": "To not know"},
        {"word": "이해하다", "meaning": "To understand"},
        {"word": "잊다", "meaning": "To forget"},
        {"word": "기억하다", "meaning": "To remember"},
        {"word": "좋아하다", "meaning": "To like"},
        {"word": "싫어하다", "meaning": "To dislike"},
        {"word": "사랑하다", "meaning": "To love"},
        {"word": "미워하다", "meaning": "To hate"},
        {"word": "살다", "meaning": "To live"},
        {"word": "죽다", "meaning": "To die"},
        
        # Adverbs
        {"word": "매우", "meaning": "Very"},
        {"word": "너무", "meaning": "Too much"},
        {"word": "아주", "meaning": "Very/Quite"},
        {"word": "정말", "meaning": "Really"},
        {"word": "진짜", "meaning": "Really/Truly"},
        {"word": "거의", "meaning": "Almost"},
        {"word": "전혀", "meaning": "Not at all"},
        {"word": "항상", "meaning": "Always"},
        {"word": "자주", "meaning": "Often"},
        {"word": "가끔", "meaning": "Sometimes"},
        {"word": "거의 안", "meaning": "Rarely"},
        {"word": "절대로", "meaning": "Never/Absolutely"},
        {"word": "빨리", "meaning": "Quickly"},
        {"word": "천천히", "meaning": "Slowly"},
        {"word": "잘", "meaning": "Well"},
        {"word": "나쁘게", "meaning": "Badly"},
        {"word": "함께", "meaning": "Together"},
        {"word": "혼자", "meaning": "Alone"},
        {"word": "직접", "meaning": "Directly"},
        {"word": "간접적으로", "meaning": "Indirectly"},
        {"word": "특히", "meaning": "Especially"},
        {"word": "일반적으로", "meaning": "Generally"},
        {"word": "오늘", "meaning": "Today"},
        {"word": "내일", "meaning": "Tomorrow"},
        {"word": "어제", "meaning": "Yesterday"},
        {"word": "지금", "meaning": "Now"},
        {"word": "나중에", "meaning": "Later"},
        {"word": "먼저", "meaning": "First/Before"},
        {"word": "마침내", "meaning": "Finally"},
        {"word": "갑자기", "meaning": "Suddenly"},
        {"word": "점점", "meaning": "Gradually"},
        {"word": "반드시", "meaning": "Definitely/Surely"},
        {"word": "아마도", "meaning": "Maybe/Perhaps"},
        {"word": "확실히", "meaning": "Certainly"},
        {"word": "약간", "meaning": "Slightly/A little"},
        {"word": "꽤", "meaning": "Quite/Fairly"},
        {"word": "완전히", "meaning": "Completely"},
        {"word": "부분적으로", "meaning": "Partially"},
        {"word": "대체로", "meaning": "Generally"},
        {"word": "주로", "meaning": "Mainly"},
        {"word": "특별히", "meaning": "Specially"},
        {"word": "분명히", "meaning": "Clearly"},
        {"word": "물론", "meaning": "Of course"},
        {"word": "왜", "meaning": "Why"},
        {"word": "어떻게", "meaning": "How"},
        {"word": "어디에", "meaning": "Where"},
        {"word": "언제", "meaning": "When"},
        {"word": "늘", "meaning": "Always"},
        {"word": "다시", "meaning": "Again"},
        {"word": "여기", "meaning": "Here"},
        {"word": "저기", "meaning": "There"}
    ]
    
    word_entry = random.choice(words)
    return word_entry["word"], word_entry["meaning"]

# Get a random Korean word and its meaning
word, meaning = get_random_korean_word()

# Save the word and meaning to files for the GitHub Action to read
with open('korean_word.txt', 'w') as f:
    f.write(word)
with open('korean_meaning.txt', 'w') as f:
    f.write(meaning)

print(f"Korean Word: {word}")
print(f"Meaning: {meaning}")
