name: Korean Word of the Day PR

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  create-word-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Fetch Korean word of the day
        id: fetch-word
        run: |
          python .github/scripts/get_korean_word.py
          echo "KOREAN_WORD=$(cat korean_word.txt)" >> $GITHUB_ENV
          echo "MEANING=$(cat korean_meaning.txt)" >> $GITHUB_ENV
        
      - name: Create new branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          today=$(date +%Y-%m-%d)
          git checkout -b word-of-the-day-$today
          
      - name: Update word file
        run: |
          echo "${{ env.KOREAN_WORD }} - ${{ env.MEANING }}" > current_word.md
          git add current_word.md
          git commit -m "Update Korean word of the day"
          git push origin word-of-the-day-$(date +%Y-%m-%d)
          
      - name: Close previous PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });
            
            const today = new Date().toISOString().split('T')[0];
            
            for (const pr of prs.data) {
              if (!pr.title.includes(today) && pr.title.includes('Korean Word of the Day')) {
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pr.number,
                  state: 'closed'
                });
              }
            }
            
      - name: Create new PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            await github.rest.pulls.create({
              owner,
              repo,
              title: `Korean Word of the Day: ${process.env.KOREAN_WORD} (${process.env.MEANING})`,
              body: `Learn a new Korean word today: **${process.env.KOREAN_WORD}** - ${process.env.MEANING}`,
              head: `word-of-the-day-${new Date().toISOString().split('T')[0]}`,
              base: 'main'
            });
